#!/bin/sh

mkdir -p ~/.var/app/org.x.hypnotix/cache/hypnotix/favorites
touch ~/.var/app/org.x.hypnotix/cache/hypnotix/favorites/list

mkdir -p ~/.var/app/org.x.hypnotix/cache/hypnotix/yt-dlp
if [ $(gsettings get org.x.hypnotix use-local-ytdlp) = true ]
then
	echo "Local version of yt-dlp selected."
	export PATH="~/.var/app/org.x.hypnotix/cache/hypnotix/yt-dlp":${PATH}
else
	echo "System version of yt-dlp selected."
fi

/app/hypnotix/lib/hypnotix/hypnotix.py &
